spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-server-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-server-test
---
spring:
  profiles: prod
  application:
    name: springcloud-config-server-prod