# 开发环境配置
server:
  port: 8004
spring:
  profiles: dev
  application:
    name: springcloud-provider-item-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.233.130:8066/gc-item
    username: root
    password: 123!@#qweQWE
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml       # mybatis配置文件所在路径
  type-aliases-package: com.yxhjeremy.api.domain           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: springcloud-provider-item-service-8004
    prefer-ip-address: true

info:
  app.name: springcloud-provider-order-service
  company.name: www.yxhjeremy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
# 测试环境配置
server:
  port: 8005
spring:
  profiles: test
  application:
    name: springcloud-provider-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.233.130:8066/gc-item
    username: root
    password: 123!@#qweQWE
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yxhjeremy.api.domain           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
  instance:
    instance-id: springcloud-provider-item-service-8005
    prefer-ip-address: true
info:
  app.name: springcloud-provider-order-service
  company.name: www.yxhjeremy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
# 生产环境配置
server:
  port: 8006
spring:
  profiles: prod
  application:
    name: springcloud-provider-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.233.130:8066/gc-item
    username: root
    password: 123!@#qweQWE
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yxhjeremy.api.domain           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-provider-item-service-8006
    prefer-ip-address: true

info:
  app.name: springcloud-provider-order-service
  company.name: www.yxhjeremy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

