# 开发环境配置
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: springcloud-provider-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://192.168.233.130:8066/gc-user
    username: root
    password: 123!@#qweQWE
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml       # mybatis配置文件所在路径
  type-aliases-package: com.yxhjeremy.api.domain           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: springcloud-provider-user-service-8001
    prefer-ip-address: true
info:
  app.name: springcloud-provider-user-service
  company.name: www.yxhjeremy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
# 测试环境配置
server:
  port: 8002
spring:
  profiles: test
  application:
    name: springcloud-provider-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://192.168.233.130:8066/gc-user
    username: root
    password: 123!@#qweQWE
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yxhjeremy.api.domain           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
  instance:
    instance-id: springcloud-provider-user-service-8002
    prefer-ip-address: true
info:
  app.name: springcloud-provider-user-service
  company.name: www.yxhjeremy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
# 生产环境配置
server:
  port: 8003
spring:
  profiles: prod
  application:
    name: springcloud-provider-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://192.168.233.130:8066/gc-user
    username: root
    password: 123!@#qweQWE
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yxhjeremy.api.domain           # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-provider-user-service-8003
    prefer-ip-address: true

info:
  app.name: springcloud-provider-user-service
  company.name: www.yxhjeremy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

