server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-eureka-server-7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---

server:
  port: 7002
spring:
  profiles: test
  application:
    name: springcloud-eureka-server-7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---

server:
  port: 7003
spring:
  profiles: prod
  application:
    name: springcloud-eureka-server-7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka